server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Racine du serveur web
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    # Servir le site statique
    location / {
        try_files $uri $uri/ =404;
    }

    # Rediriger toutes les requêtes /api vers FastAPI
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
