name: MaBoule CI/CD Pipeline

on:
  push:
    branches:
      - TP2
  workflow_dispatch:

jobs:
  deploy:
    name: Déploiement Terraform & Ansible
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v7

      - name: ☁️ Configuration des identifiants AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: 🏗️ Installation de Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.11.0"

      - name: 🚀 Terraform Init
        run: make init

      - name: 🌍 Terraform Apply
        run: make apply-auto

      - name: 🔍 Récupération de l'IP du serveur
        working-directory: ./envs/dev-aws
        id: get_ip
        run: |
          EC2_IP=$(terraform output -raw ip_publique)
          echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT
          echo "L'adresse IP déployée est $EC2_IP"

      - name: 🐍 Installation de Python et Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip

      - name: 🔑 Configuration de la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/labsuser-2.pem
          chmod 400 ~/.ssh/labsuser-2.pem
          # Éviter les prompts SSH de validation d'hôte (Host Key Checking)
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" > ~/.ssh/config

      - name: ⚙️ Configuration du serveur avec Ansible
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          # Création dynamique de l'inventaire avec l'IP récupérée de Terraform
          echo "[webservers]" > inventory_ci.ini
          echo "${{ steps.get_ip.outputs.ec2_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/labsuser-2.pem" >> inventory_ci.ini
          
          # Exécution du playbook
          ansible-playbook -i inventory_ci.ini playbook.yml
