name: Destruction Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Suppression Terraform
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v7

      - name: ☁️ Configuration des identifiants AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: 🏗️ Installation de Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.11.0"

      - name: 🚀 Terraform Init
        run: make init

      - name: 💣 Terraform Destroy
        run: make destroy-auto
