name: Terraform CI

on:
  push:
    branches: [ "TP2" ]
  pull_request:
    branches: [ "TP2" ]

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: ☁️ Configuration des identifiants AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.11.0"

    - name: Terraform Format
      id: fmt
      run: make fmt-check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: make init

    - name: Terraform Validate
      id: validate
      run: make validate

    - name: Terraform Plan
      id: plan
      run: make plan
      continue-on-error: true

  security:
    name: Security Scanners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          working_directory: ./envs/dev-aws
          github_token: ${{ github.token }}
        continue-on-error: true

      - name: 🛡️ Trivy - Analyse complète (Vulnérabilités, Secrets, IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,secret,config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
