name: Terraform CI

on:
  push:
    branches: [ "TP2" ]
  pull_request:
    branches: [ "TP2" ]

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./envs/dev-aws

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.0"

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -var="cidr_admin=0.0.0.0/0"
      continue-on-error: true

  security:
    name: Security Scanners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          working_directory: ./envs/dev-aws
          github_token: ${{ github.token }}
        continue-on-error: true

      - name: 🛡️ Trivy - Analyse complète (Vulnérabilités, Secrets, IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln,secret,config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
